% very basic script to print Minerva first round values in Latex
% table
% run first_round_preds_10_2020 first


for i=1:size(states,1)
        fprintf('%s & %1.4f & %d & %d & %1.4f \\\\ \\hline \n', states{i}, ...
            margin_many(i), ...
            distinct_B(i), ...
            distinct(i), ...
            distinct_factor_many(i)) 
end