% very basic script to read Athena first round values and print in Latex
% table
fname='2016_one_round_all.json';
election_results = jsondecode(fileread(fname));
states = fieldnames(election_results);


for i=1:size(states,1)
    if i==23 % Computed using estimate_first_round_Arlo and scaled
        fprintf('%s & %1.4f & %d & %d & 0.4810 \\\\ \\hline \n', states{i}, ...
            abs(election_results.(states{i}).contests.presidential.margin), ...
            2618926, ...
            1259688)
    elseif i==
    else
        fprintf('%s & %1.4f & %d & %d & %1.4f \\\\ \\hline \n', states{i}, ...
            abs(election_results.(states{i}).contests.presidential.margin), ...
            election_results.(states{i}).contests.presidential.Arlo_pv_scaled, ...
            election_results.(states{i}).contests.presidential.Athena_pv_scaled, ...
            election_results.(states{i}).contests.presidential.Athena_pv_scaled/...
            election_results.(states{i}).contests.presidential.Arlo_pv_scaled) 
    end
end